// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADnMCwXBMbnq1W_8kHVc19vTxCoDpRRGY',
    appId: '1:1084741784734:web:97b769d2dcabb4aee2978f',
    messagingSenderId: '1084741784734',
    projectId: 'e-navit',
    authDomain: 'e-navit.firebaseapp.com',
    databaseURL: 'https://e-navit-default-rtdb.firebaseio.com',
    storageBucket: 'e-navit.appspot.com',
    measurementId: 'G-RY0RVD9DWM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3xdXpZ_CWyvqnHe6PjaEVz-dYsCpRydU',
    appId: '1:1084741784734:android:e31ef7588490b9b9e2978f',
    messagingSenderId: '1084741784734',
    projectId: 'e-navit',
    databaseURL: 'https://e-navit-default-rtdb.firebaseio.com',
    storageBucket: 'e-navit.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMtgBHzjBpOEdfoCk11MNNLojozju6x88',
    appId: '1:1084741784734:ios:c2a23a1e6cdad78fe2978f',
    messagingSenderId: '1084741784734',
    projectId: 'e-navit',
    databaseURL: 'https://e-navit-default-rtdb.firebaseio.com',
    storageBucket: 'e-navit.appspot.com',
    iosClientId: '1084741784734-te2njtircngtqiquhrcs7uagehlunel6.apps.googleusercontent.com',
    iosBundleId: 'com.example.enavit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMtgBHzjBpOEdfoCk11MNNLojozju6x88',
    appId: '1:1084741784734:ios:c2a23a1e6cdad78fe2978f',
    messagingSenderId: '1084741784734',
    projectId: 'e-navit',
    databaseURL: 'https://e-navit-default-rtdb.firebaseio.com',
    storageBucket: 'e-navit.appspot.com',
    iosClientId: '1084741784734-te2njtircngtqiquhrcs7uagehlunel6.apps.googleusercontent.com',
    iosBundleId: 'com.example.enavit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADnMCwXBMbnq1W_8kHVc19vTxCoDpRRGY',
    appId: '1:1084741784734:web:79729532c084f480e2978f',
    messagingSenderId: '1084741784734',
    projectId: 'e-navit',
    authDomain: 'e-navit.firebaseapp.com',
    databaseURL: 'https://e-navit-default-rtdb.firebaseio.com',
    storageBucket: 'e-navit.appspot.com',
    measurementId: 'G-EE0P9W6FDX',
  );
}
